### ISSUE TITLE
Web Socket Support

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#155]
Use the `ws` library and get web sockets up and running with monument!

**Comment by designfrontier** [comment]
@britton-jb Initial implementation is happening on the `feature/web-socket-built-in` branch currently supports all `data:get:what-ever` events properly. Feel free to grab it and test it out locally and let me know what you think.

What do you about route events? Should it handle them as well? Right now I am leaning towards no simply because they are generally returning html as opposed to data and sending html over a websocket feels like back when we used jquery to grab rendered partials from the server. ![sad panda](https://media4.giphy.com/media/Q3Ou3eFKMTFn2/200.gif)

But if you think this would be valuable... I am open to being persuaded.

**Comment by britton-jb** [comment]
The only compelling argument I've seen for route events over websockets is giving a restful interface to your application that's still accessible in a restful manner. That said, I think this would be a great initial implementation.

**Comment by designfrontier** [comment]
@britton-jb Just pushed a newer version with much broader support for events. Documentation is in [doc/websocket.md](https://github.com/ansble/monument/blob/feature/websocket-built-in/docs/websockets.md) take a look, grab the branch and give it a try. Let me know what you think. It still lacks good unit tests around the server code... but I am much happier with where this is right now.

**Comment by britton-jb** [comment]
@designfrontier That looks great to me. That was actually how I was thinking about approaching it as well. Gives you a really cool way to interact with the server on the client in my opinion.

**Comment by designfrontier** [comment]
Once I get some tests written I'll get this merged into the release branch then

**Comment by designfrontier** [comment]
merged into la-fleche release branch!
