### ISSUE TITLE
Monument new doesn't use the specified path

### ISSUE THREAD

**Issue by britton-jb** [ansble/monument#174]
When I run the following:

- `monument new myApp`
- `monument new ./myApp`
- `monument new ./myApp/`
- `monument new myApp/`

It creates the app in the current directory, rather than the specified.

**Comment by designfrontier** [comment]
Wow... not sure how that slipped through. Will get that fixed up. Thanks for finding it @britton-jb

**Comment by designfrontier** [comment]
Fixed by https://github.com/ansble/monument-cli/pull/39

**Comment by designfrontier** [comment]
@britton-jb if you install the latest release (1.0.7) of `monument-cli` this is fixed and you should be good to go
