### ISSUE TITLE
Run through the code base and create tickets for any TODO items

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#182]
There are some TODOs listed in the code base that don't have corresponding tickets in the issues. Run through and create a ticket for them here. Pick up any you would like to complete.

**Comment by hemantjadon** [comment]
Hi, I am new in the open-source,
can you please tell exactly what needs to be done.

#### My understanding of issue : 
Make github hook to check code after each commit to master,
search for `# Todo` , in code base and and open a github ticket for that issue.

**Comment by designfrontier** [comment]
@hemantjadon I am seeing this super late, which I am sorry for. But yes. You understand exactly.

**Comment by JensGryspeert** [comment]
Seems this ticket is still open. @designfrontier  is there anything done for this already? If not I'm happy to contribute for this.

**Comment by chadapohn** [comment]
Hi @designfrontier, can I give this one a go? :)

**Comment by designfrontier** [comment]
Sure thing. Post any tickets you open in a comment here!

**Comment by designfrontier** [comment]
All todos are gone
