### ISSUE TITLE
Expand test coverage in the router.js file

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#195]
https://coveralls.io/builds/4658528 Looks like it is covered about 75%...

Locally you can get this number by running `npm test`. That creates an output to console and the more useful coverage directory. In the coverage directory (run it with a static server like `http-server`) you can drill into the coverage in the browser and see exactly what lines are not tested currently.

**Comment by RS-Crawford** [comment]
@designfrontier :
Hey there! I did some work on this. I'd love to see if you can use any of it. You can find it here:

https://github.com/RS-Crawford/monument/blob/features/routes/router_test.js

Should be at the bottom, under the header "compression routes". Thanks.

**Comment by designfrontier** [comment]
do you mind sending a pull request so I can review this against the latest code base? It looks good from the brief glance I took at it this morning.
