### ISSUE TITLE
Expand test coverage in the web-sockets/socketHandler.js file

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#196]
https://coveralls.io/builds/4658528 Looks like it is covered about 86%...

Locally you can get this number by running `npm test`. That creates an output to console and the more useful coverage directory. In the coverage directory (run it with a static server like `http-server`) you can drill into the coverage in the browser and see exactly what lines are not tested currently.

**Comment by designfrontier** [comment]
@kcneagle this one is a little more complicated then the other but it's also writing additional tests that cover edges that the existing ones miss.

**Comment by lazycoder9** [comment]
Done https://github.com/ansble/monument/pull/470
