### ISSUE TITLE
Add a working example of the websockets code

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#213]
Add a working example to the documentation for web sockets to make it easier to understand how to use them an integrate with them

**Comment by piecedigital** [comment]
I'm attempting to get a working example...

I'm having trouble understanding this myself. So far my attempts at getting it to not throw errors is making everything more complicated than necessary.

**Comment by designfrontier** [comment]
Yeah I am going to take a look at your PR with the fix in it. I started working up better tests around it and an example and ran into the same thing.

Thanks for your help!
