### ISSUE TITLE
route api not detailed in the main readme

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#258]
Under `monument's API` There should be a note and links to deeper documentation.

The main documentation is in `/docs/routes.md`. The best approach is probably to write a simple summary for the [monument api section](https://github.com/ansble/monument#monuments-api) of the main readme.md file. The other sections their should be good examples.

Once that is done link to the `/docs/routes.md` file for more information.

**Comment by cosmologist10** [comment]
Looks good to me! I'm working on this issue.

**Comment by designfrontier** [comment]
thanks @cosmologist10
