### ISSUE TITLE
update to latest glob

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#260]
update the dependency on `glob` to the latest version. 

Make sure nothing breaks by running through the test suite and making sure they all still pass.

**Comment by andmckvr13** [comment]
@designfrontier I'm new to contributing, but would like to try to help with this if I can. Is this the line that needs to be updated? https://github.com/ansble/monument/blob/9cc878fe804880fd6a7e5b7612c62d142c9d29e5/package.json#L45

**Comment by designfrontier** [comment]
It sure is. Then just make sure that all the tests still pass by running them according to the instructions in the contributing file.

-Daniel

**Comment by designfrontier** [comment]
#284 merged this into the next release branch
