### ISSUE TITLE
Expand test coverage in the security/contentSecurityPolicy.js file

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#264]
https://coveralls.io/builds/8057449/source?filename=security%2FcontentSecurityPolicy.js Looks like it is covered about 98%...

Locally you can get this number by running npm test. That creates an output to console and the more useful coverage directory. In the coverage directory (run it with a static server like http-server) you can drill into the coverage in the browser and see exactly what lines are not tested currently.

**Comment by designfrontier** [comment]
@kcneagle this might be a good one to tackle, it is basically adding another browser User Agent that hits the missed case in the link above.

**Comment by kcnaegle** [comment]
Cool, I'll take a look! Thanks!

**Comment by designfrontier** [comment]
closed by #513
