### ISSUE TITLE
Add server timings header for much win

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#324]
As an example I give you this express  middleware: https://www.npmjs.com/package/server-timings for reverse engineering.

Should most likely integrate nicely in parallel to the statsd stuff that is already in place.

**Comment by Vishwajeetsinh98** [comment]
@designfrontier Do you wish to use the same middleware or do you wish to create a custom middleware?

**Comment by designfrontier** [comment]
@Vishwajeetsinh98 Since monument doesn't have the concept of middleware this will be new stuff. Should be built in to the route handling code somewhere.

The middleware is referenced because it is a good reference point for the things that are measured and that are expected on the browser side as far as headers.

**Comment by Vishwajeetsinh98** [comment]
Okay, I will check the route handling code for desirable places to put the code. Will revert shortly.

**Comment by designfrontier** [comment]
Currently under development in the branch above

**Comment by designfrontier** [comment]
This is complete... just waiting on the 3.3.0 release. See #466
