### ISSUE TITLE
Lock down dependencies to specific versions

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#429]
remove any wiggle room with `~` and replace with specific versions

**Comment by elementh** [comment]
Can I take this? 👍

**Comment by designfrontier** [comment]
Please do!

**Comment by stofolus** [comment]
It might be a good idea to use a `package.lock` file as well to prevent sub-dependencies from updating. 
https://docs.npmjs.com/files/package-locks

**Comment by designfrontier** [comment]
that would be awesome @elementh do you mind adding that to your pull request?

**Comment by elementh** [comment]
@designfrontier consider it done!
