### ISSUE TITLE
provide a way to insert a log function

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#444]
For logging errors/debug/info messages out of the internals of monument.

This would allow for the passing in of something like bunyan with the default going to console.log, console.debug and consolu.info.

This will make it easier to stub out the tests and information.

Should be passed in as part of the config object for the server

**Comment by dottorblaster** [comment]
I'd like to work on this. 😬

**Comment by designfrontier** [comment]
@dottorblaster all yours!

**Comment by dottorblaster** [comment]
I have a question: do you have any preference about the API that such function should have? I was thinking about a `(level, payload) => { ... }` and then do somwthing inside, but I don't know if you already thought about a convention or something like that.

**Comment by designfrontier** [comment]
I was thinking something along the lines of passing in a logger object that has an API like bunyan (for some reason they only really lay this out in the browserify section: https://www.npmjs.com/package/bunyan#browserify)

```
log.trace('this one does not emit');
log.debug('hi on debug');   // console.log 
log.info('hi on info');     // console.info 
log.warn('hi on warn');     // console.warn 
log.error('hi on error');   // console.error 
```

So we would accept in the log object, defaulting the values to console like above. This should make it pretty easy to use bunyan, and most other loggers. So the config of a new monument server would just receive `log` and run with it. Probably want to stub trace to a `noop` the rest could be a straight `console` as seen above.

Let me know if this makes sense... or doesn't.

**Comment by dottorblaster** [comment]
It does. I'll try poking things as soon as possible, looks good!

**Comment by designfrontier** [comment]
Thanks a million!
