### ISSUE TITLE
update the documentation around the connection object

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#449]
There is now a path key in the connection object sent everywhere. It needs to be documented in the readme, have tests ensuring it is there. That's probably enough for this ticket.

**Comment by glhrmv** [comment]
I'm going to take a crack at this.

**Comment by glhrmv** [comment]
I've already done a few grammar fixes throughout the source files. I'm unsure exactly which "path key" in the connection object you're referring to, but I'm guessing it's the `publicPath` one. Could you clarify this for me, though?

**Comment by glhrmv** [comment]
I've submitted #453 which includes those small quality of life text updates. I'm still interested in this issue but there are 3 "path" keys in the config object and they're all present in the main readme.

**Comment by designfrontier** [comment]
@glhrmv So the path key I am talking about is `connection.path` which is exposed here:  https://github.com/ansble/monument/blob/master/routes/router.js#L52

It is available to all route listeners in the connection object that they receive,  but hasn't been documented yet, like the rest of that object. The existing documentation is in the main `readme.md` file under Route API.

`connection.path` is a parsed url (as parsed by url parser in `utils/url.js`)

**Comment by glhrmv** [comment]
Don't have the time to look at this right now unfortunately so I'm letting everyone know they're free to take this on. Good luck 👍

**Comment by zberwaldt** [comment]
Hello, 

Read through this thread and thought I would give resolving this a shot.

**Comment by zberwaldt** [comment]
Just to be safe, I'm just commenting that I've made additional commits to the pull request for this issue.
