### ISSUE TITLE
Expand Test Coverage on `utils/statsd.js` to 100%

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#460]
https://coveralls.io/builds/13642948/source?filename=utils%2Fstatsd.js Looks like it is covered about 66%...

Locally you can get this number by running npm test. That creates an output to console and the more useful coverage directory. In the coverage directory (run it with a static server like http-server) you can drill into the coverage in the browser and see exactly what lines are not tested currently.

**Comment by lazycoder9** [comment]
I'll take it

**Comment by designfrontier** [comment]
This will go out in the release tomorrow morning! Thanks again!
