### ISSUE TITLE
Expand test coverage on `utils/index.js` to 100%

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#461]
https://coveralls.io/builds/13642948/source?filename=utils%2Findex.js Looks like it is covered about 83%...

Locally you can get this number by running npm test. That creates an output to console and the more useful coverage directory. In the coverage directory (run it with a static server like http-server) you can drill into the coverage in the browser and see exactly what lines are not tested currently.

**Comment by geritol** [comment]
Seems to be an interesting task! I will pick up a cuck of this I think!

**Comment by designfrontier** [comment]
Will cut a release with these changes tomorrow morning

**Comment by geritol** [comment]
Cool!
