### ISSUE TITLE
Add keywords to the package.json

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#52]
server
http
https
web
webserver
web server
framework
api
app
rest
restful

**Comment by designfrontier** [comment]
use the milan-san-remo branch as your base for this

**Comment by kentcdodds** [comment]
lol is this for real?

**Comment by designfrontier** [comment]
yep

**Comment by kentcdodds** [comment]
hilarious

**Comment by designfrontier** [comment]
I am in the middle of etags and realized this needed to be done... thought I would give some one else the opportunity to do it ;-)
