### ISSUE TITLE
Provide way to change dotjs configuration.

### ISSUE THREAD

**Issue by uniqname** [ansble/monument#73]
Default configuration for dotjs.strip is true which was causing a `Uncaught SyntaxError: Unexpected end of input` error. When set to false, the error went away. There doesn't seem to be a way to change the configuration while using monument.

**Comment by uniqname** [comment]
Addressed with [PR-74](https://github.com/ansble/monument/pull/74)

**Comment by designfrontier** [comment]
Thanks! Got it merged in and released in [1.4.3](https://github.com/ansble/monument/commit/b29d21ad508fef969a069f3e2a4e2f4e36bf6550)
