### ISSUE TITLE
Handle `?someList[]=value` convention

### ISSUE THREAD

**Issue by uniqname** [ansble/monument#79]
There is a convention where parameter keys are suffix with `[]` indicating multiple values are expected. Monument should handle this convention elegantly. @eatrocks is currently working on a pull request addressing this.

**Comment by designfrontier** [comment]
@eatrocks: you're working this right?

**Comment by eatrocks** [comment]
yep'r. I have a potential fix but in my testing it failed. I think I didn't properly identify the proper insertion point.  Working on that now.

**Comment by designfrontier** [comment]
Do you have an ETA on it @eatrocks?
